# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Onboarding
tagline:             ''
description:         ''
url:                 rajdeepd.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Rajdeep Dua
  url:               https://twitter.com/rajdeepdua
  email:             reudismam@copin.ufcg.edu.br
  
#Sidebar
github:
  repo               https://github.com/rajdeepd

# Custom vars
version:             1.0.0
